apiVersion: 1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector: 
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      -  name: rohan-demo
         image: arjunachari12/k8s-demo
         ports:
         -  name: nodejs-port
            containerPort: 3000
      
