apiVersion: v1
kind: Pod
metadata:
  name: nodenginx.example.com
  labels:
    app: helloworld
spec:
  containers:
  -  name: rohan-demo
     image: nginx
     ports:
     -  name: nodejs-port
        containerPort: 80
